apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: knytssmailandstuff
spec:
  build:
    secrets:
      - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "efef90d1-b530-4fb5-a06f-f9d4d5b538ad"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET